seed: 0
model:
  model_type: S4Model
  model_dim: 512
  state_dim: 32
data:
  data_path: data/camelyon16
  folds_path: folds/camelyon16
  n_classes: 2
  input_dim: 1024
  fold: 0
  batch_size: 1
training:
  optimizer: Adam
  use_lookahead: True
  lr: 0.0002
  wd: 0.00001
  patience: 10
  max_epochs: 200
  loss: CrossEntropyLoss
  save_path: outputs/camelyon16